### ISSUE TITLE
Crash when importing pykep on Mac OS

### ISSUE THREAD

**Issue by BookOwl** [esa/pykep#107]
After installing pykep using conda for Python 3.7 on MacOS, running `import pykep as pk` gives the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matthew/anaconda3/lib/python3.7/site-packages/pykep/__init__.py", line 48, in <module>
    from pykep import core, sims_flanagan, pontryagin, orbit_plots, examples, phasing, util, planet, trajopt
  File "/Users/matthew/anaconda3/lib/python3.7/site-packages/pykep/pontryagin/__init__.py", line 4, in <module>
    from ._leg import leg
  File "/Users/matthew/anaconda3/lib/python3.7/site-packages/pykep/pontryagin/_leg.py", line 1, in <module>
    from pykep.pontryagin._dynamics import _dynamics
  File "/Users/matthew/anaconda3/lib/python3.7/site-packages/pykep/pontryagin/_dynamics.py", line 6, in <module>
    class _dynamics(object):
  File "/Users/matthew/anaconda3/lib/python3.7/site-packages/pykep/pontryagin/_dynamics.py", line 8, in _dynamics
    def __init__(self, sc=spacecraft(1000, 0.3, 2500), mu=MU_SUN, alpha=1, bound=True):
TypeError: __init__() should return None, not 'NoneType'
```

**Comment by darioizzo** [comment]
cannot reproduce. conda CI is able to import and test pyep succesfully on osx py36, 37 and 38.

Feel free to reopen if your problem persists, in which case gives us more details.
