### ISSUE TITLE
Install through conda

### ISSUE THREAD

**Issue by pmirallesr** [esa/pykep#132]
If I've understood the procedure correctly (I'm a beginner), this procedure should be enough to install all of pykep:
```
$ conda config --add channels conda-forge
$ conda config --set channel_priority strict
$ conda install pykep
```

However upon doing so, I had no access to the pk.test module
```
>>> pykep.test.run_test_suite()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pykep' has no attribute 'test'
```
or examples module
```
>>> pk.examples.run_example4(nseg=20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pykep' has no attribute 'examples'
```
Is this a mistake from my part / expected behaviour?

**Comment by pmirallesr** [comment]
Found out that I have to install pygmo with SNOPT7 to run this example. Sorry!
