### ISSUE TITLE
Importing pykep returns ImportError upon calling dlopen

### ISSUE THREAD

**Issue by carson-cheng** [esa/pykep#164]
I am using an M1 Mac on macOS 13.0.1, and I'm running Python 3.11. When I tried to import the pykep module after installing it in a rather unusual way, I got this error:

```
~ % python3
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pykep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carsoncheng/Library/Python/3.11/lib/python/site-packages/pykep/__init__.py", line 55, in <module>
    from pykep.core import *
  File "/Users/carsoncheng/Library/Python/3.11/lib/python/site-packages/pykep/core/__init__.py", line 3, in <module>
    from .core import _get_AU, _get_JR, _get_DAY2SEC, _get_DAY2YEAR, _get_DEG2RAD, _get_EARTH_VELOCITY, _get_EARTH_J2, _get_EARTH_RADIUS, _get_MU_EARTH, _get_G0, _get_MU_SUN, _get_RAD2DEG, _get_SEC2DAY
ImportError: dlopen(/Users/carsoncheng/Library/Python/3.11/lib/python/site-packages/pykep/core/core.so, 0x0002): tried: '/Users/carsoncheng/Library/Python/3.11/lib/python/site-packages/pykep/core/core.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/carsoncheng/Library/Python/3.11/lib/python/site-packages/pykep/core/core.so' (no such file), '/Users/carsoncheng/Library/Python/3.11/lib/python/site-packages/pykep/core/core.so' (not a mach-o file)
```

Also, it doesn't look like the problem specified in previous issues were fixed because pykep is still unavailable through pip (even though it contains an entry at the PyPi database (https://pypi.org/project/pykep/). That means I have to manually download version 2.6 (from October 2020) there.

Are there any workarounds for this problem or ways to address this issue?

**Comment by carson-cheng** [comment]
Remember to use the conda environment for installation, and remember to move the file back to the correct location (I thought the conda installation also failed because it's on the wrong path!)
